import axios from 'axios';

export interface MessageSearch {
    messageId?: number;
    qCode?: string;
    airSpaceCodeId?: string;
    type?: string;
    validType?: string;
    lat?: string;
    long?: string;
    radius?: string;
    telegramText?: string;
    startTime: string;
    endTime: string;
    pageIndex: number;
    pageSize: number;
}
export interface MessageVM {
    qCode: string;
    airSpaceCodeId: string;
    type: string;
    validType: string;
    lat: string;
    long: string;
    radius: string;
    telegramText: string;
    templateId: number;
    workflowId: number;
    parentId: number;
    startTime: string;
    endTime: string;
    specialNotes:string;
}
export interface MessageWorkflowVM {
    messageId: number;
    workflowId: string;
}
export interface PublishVM {
    messageId: number;
    state: string;
}
export interface CreateWorkflowVM {
    messageId: number;
    templateId: string;
    authUserId: string;
    authorization: string;
    flyflowTenantId: string;
}
// 定义返回数据类型
export interface ProgressRequest {
    processInstanceId: string;
    flowId: string;
    flyflowTenantId?: string; // 可选，后端默认"1"
    authUserId?: string;      // 可选
    authorization?: string;   // 可选
}
// 定义返回数据类型
export interface WorkflowAuditRequest {
    processInstanceId: string;
    flowId: string;
    taskId: string;
    approveDesc: string;
    approveResult: string;
    flyflowTenantId?: string; // 可选，后端默认"1"
    authUserId?: string;      // 可选
    authorization?: string;   // 可选
}

export function queryMessageList(params: MessageSearch) {
    return axios.get('/message/list', { params });
}
export function queryMessageDetail(params: { id: number }) {
    return axios.get('/message/get', {
        params,
    });
}
export function deleteMessage(ids: []) {
    return axios.post('/message/delete', ids);
}
export function postMessage(data: MessageVM) {
    return axios.post<MessageVM>('/message/post', data);
}
export function postBatchMessage(data:  MessageVM[]) {
    return axios.post<MessageVM[]>('/message/batchpost', data);
}
export function createWorkflow(data: CreateWorkflowVM) {
    return axios.post<MessageVM>('/message/createworkflow', data);
}
export function postWorkflowId(data: MessageWorkflowVM) {
    return axios.post<MessageWorkflowVM>('/message/postworkflowid', data);
}
export function queryGetWorkflowProgress(data: ProgressRequest) {
    return axios.post<ProgressRequest>('/message/getworkflowprogress', data);
}
export function publishMessage(data: PublishVM) {
    return axios.post<PublishVM>('/message/publish', data);
}
export function queryGetRelateMessage(params: { id: number }) {
    return axios.get('/message/getrelatemessage', {
        params,
    });
}

export function SubmitWorkflowAudit(data: WorkflowAuditRequest) {
    return axios.post<WorkflowAuditRequest>('/message/submitworkflowaudit', data);
}

export function fetchAutoGeneratedNotamSn() {
    return axios.get('/message/getautogeneratednotamsn');
}